### PR TITLE
LUA SWIG changes 

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
Doing a 'make distcheck' it errors out as follows:

```Making check in tests
make[2]: Entering directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'
make  dumpmem testrig testtrn testbcd testfreq listrigs testloc rig_bench testrig.sh testfreq.sh testbcd.sh testloc.sh
make[3]: Entering directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'
  CC       dumpmem.o
../../../tests/dumpmem.c: In function ‘main’:
../../../tests/dumpmem.c:91:45: error: ‘chan_t’ {aka ‘struct chan_list’} has no member named ‘start’; did you mean ‘startc’?
         for (j = my_rig->state.chan_list[i].start;
                                             ^~~~~
                                             startc
../../../tests/dumpmem.c:92:46: error: ‘chan_t’ {aka ‘struct chan_list’} has no member named ‘end’; did you mean ‘endc’?
              j <= my_rig->state.chan_list[i].end; j++)
                                              ^~~
                                              endc
make[3]: *** [Makefile:1054: dumpmem.o] Error 1
make[3]: Leaving directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'
make[2]: *** [Makefile:1633: check-am] Error 2
make[2]: Leaving directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'
```

**Comment by mdblack98** [comment]
Fixed it...
de Mike W9MDB

 

    On Friday, August 23, 2019, 07:03:07 AM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 
Doing a 'make distcheck' it errors out as follows:
make[2]: Entering directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'
make  dumpmem testrig testtrn testbcd testfreq listrigs testloc rig_bench testrig.sh testfreq.sh testbcd.sh testloc.sh
make[3]: Entering directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'
  CC       dumpmem.o
../../../tests/dumpmem.c: In function ‘main’:
../../../tests/dumpmem.c:91:45: error: ‘chan_t’ {aka ‘struct chan_list’} has no member named ‘start’; did you mean ‘startc’?
         for (j = my_rig->state.chan_list[i].start;
                                             ^~~~~
                                             startc
../../../tests/dumpmem.c:92:46: error: ‘chan_t’ {aka ‘struct chan_list’} has no member named ‘end’; did you mean ‘endc’?
              j <= my_rig->state.chan_list[i].end; j++)
                                              ^~~
                                              endc
make[3]: *** [Makefile:1054: dumpmem.o] Error 1
make[3]: Leaving directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'
make[2]: *** [Makefile:1633: check-am] Error 2
make[2]: Leaving directory '/home/nate/git/hlb/hamlib-4.0~git/_build/sub/tests'

**Comment by N0NB** [comment]
This error occurs in my Windows binary build:

```
Making install in winradio
make[1]: Entering directory '/home/nate/builds/hamlib-4.0~git/winradio'
  CC       wr1000.lo
  CC       wr1500.lo
  CC       wr1550.lo
  CC       wr3100.lo
  CC       wr3150.lo
  CC       wr3500.lo
  CC       wr3700.lo
  CC       g303.lo
g303.c:145:25: error: unknown field ‘start’ specified in initializer
   .rx_range_list1 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                         ^
g303.c:145:41: error: unknown field ‘end’ specified in initializer
   .rx_range_list1 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                                         ^
g303.c:149:25: error: unknown field ‘start’ specified in initializer
   .rx_range_list2 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                         ^
g303.c:149:41: error: unknown field ‘end’ specified in initializer
   .rx_range_list2 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                                         ^
Makefile:522: recipe for target 'g303.lo' failed
make[1]: *** [g303.lo] Error 1
make[1]: Leaving directory '/home/nate/builds/hamlib-4.0~git/winradio'
Makefile:605: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by mdblack98** [comment]
Had to fix a few of more...try again.
de Mike W9MDB

 

    On Friday, August 23, 2019, 06:37:07 PM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 
This error occurs in my Windows binary build:
Making install in winradio
make[1]: Entering directory '/home/nate/builds/hamlib-4.0~git/winradio'
  CC       wr1000.lo
  CC       wr1500.lo
  CC       wr1550.lo
  CC       wr3100.lo
  CC       wr3150.lo
  CC       wr3500.lo
  CC       wr3700.lo
  CC       g303.lo
g303.c:145:25: error: unknown field ‘start’ specified in initializer
   .rx_range_list1 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                         ^
g303.c:145:41: error: unknown field ‘end’ specified in initializer
   .rx_range_list1 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                                         ^
g303.c:149:25: error: unknown field ‘start’ specified in initializer
   .rx_range_list2 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                         ^
g303.c:149:41: error: unknown field ‘end’ specified in initializer
   .rx_range_list2 =  { {.start = kHz(9),.end = MHz(30),.modes = G303_MODES,
                                         ^
Makefile:522: recipe for target 'g303.lo' failed
make[1]: *** [g303.lo] Error 1
make[1]: Leaving directory '/home/nate/builds/hamlib-4.0~git/winradio'
Makefile:605: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by N0NB** [comment]
Applied and pushed.  Thanks, Mike.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Pull request merged**
