### PR TITLE
Add Rohdes&Schwarz xk2100 backend for W1AW

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
Congrats on being #1, Mike!

Do you think we should include this in 3.2 or wait?

**Comment by N0NB** [comment]
The compiler on Slackware 14.2 complained about the comments on lines 35 and 36 in xk2100.c:

`  CC       xk2100.lo
../../../rs/xk2100.c:35:1: warning: multi-line comment [-Wcomment]
 //#define XK2100_LEVEL_ALL (RIG_LEVEL_ATT|RIG_LEVEL_SQL|RIG_LEVEL_AGC|\
 ^
`
So I changed them to C multiline comments and rebased onto your patch.  Hopefully, that won't cause you a problem...

**Comment by mdblack98** [comment]
No problem.....I left that deliberately to slap me in the face about some still-needed work.My gcc just complains about a multi-line comment.


----------------------------------- 
Michael D. Black 

    On Wednesday, March 7, 2018, 2:54:44 PM CST, Nate Bargmann <notifications@github.com> wrote:  
 
 
The compiler on Slackware 14.2 complained about the comments on lines 35 and 36 in xk2100.c:

CC xk2100.lo ../../../rs/xk2100.c:35:1: warning: multi-line comment [-Wcomment] //#define XK2100_LEVEL_ALL (RIG_LEVEL_ATT|RIG_LEVEL_SQL|RIG_LEVEL_AGC|\ ^
So I changed them to C multiline comments and rebased onto your patch. Hopefully, that won't cause you a problem...

**Comment by mdblack98** [comment]
I guess I don't have to try harder then :-)
Don't see why we can't include it in 3.2.  This was mainly for WSJT-X and I think Bill just pulls the current head of hamlib so 3.2 doesn't probably matter for WSJT-X since he'l get 3.3 anyways.

Mike 

    On Wednesday, March 7, 2018, 2:29:36 PM CST, Nate Bargmann <notifications@github.com> wrote:  
 
 
Congrats on being #1, Mike!

Do you think we should include this in 3.2 or wait?

**Pull request closed without merging**
