### PR TITLE
Re-enable Yaesu question mark handling and fix newcat_get_cmd retries in case of question mark response

### LINKED ISSUE #505: Yaesu retries not working
Mikael -- need to narrow down the question_mark_response_means_rejected flag usage

If it's only needed by mode for certain rigs than it should be coded by mode for certain rigs.
The comment doesn't say what rigs this applies to.
Right now it's disallowing IF; command repeats for all Yaesu rigs and appears as though the flag doesn't get reset in all paths.
The rig_get_mode

https://github.com/Hamlib/Hamlib/commit/956be046e748066577a34508cbfe68718954edcf

On Monday, January 11, 2021, 04:38:33 PM CST, Bill Somerville <g4wjs@classdesign.com> wrote:

Rather more concerning is that while testing with the master HEAD commit I see that retries when a Yaesu rig returns a rig busy status '?;' are no longer being done. I see several examples, why is '?;' now being treated as a fatal command rejection error ratther than a rig busy condition that can be retried?

warning: [22:08:25.820593][RIGCTRL][debug] () : rig_get_mode called
warning: [22:08:25.820593][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:25.822594][RIGCTRL][trace] () : rig_get_mode: cache check age=1000000ms
warning: [22:08:25.822594][RIGCTRL][trace] () : rig_get_mode: cache miss age=1000000ms
warning: [22:08:25.823594][RIGCTRL][debug] () : newcat_get_mode called
warning: [22:08:25.823594][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:25.824595][RIGCTRL][trace] () : newcat_valid_command MD
warning: [22:08:25.824595][RIGCTRL][trace] () : newcat_set_vfo_from_alias: alias vfo = currVFO
warning: [22:08:25.825597][RIGCTRL][trace] () : newcat_get_mode: cmd_str = MD0;
warning: [22:08:25.826598][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:25.826598][RIGCTRL][debug] () : serial_flush called
warning: [22:08:25.827598][RIGCTRL][debug] () : tcflush
warning: [22:08:25.988704][RIGCTRL][trace] () : cmd_str = MD0;
warning: [22:08:25.988704][RIGCTRL][debug] () : write_block called
warning: [22:08:25.995710][RIGCTRL][trace] () : write_block(): TX 4 bytes
warning: [22:08:25.995710][RIGCTRL][trace] () : 0000    4d 44 30 3b                                         MD0;
warning: [22:08:25.996711][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:26.040742][RIGCTRL][trace] () : read_string(): RX 5 characters
warning: [22:08:26.040742][RIGCTRL][trace] () : 0000    4d 44 30 32 3b                                      MD02;
warning: [22:08:26.041741][RIGCTRL][trace] () : newcat_get_cmd: read count = 5, ret_data = MD02;
warning: [22:08:26.041741][RIGCTRL][debug] () : newcat_rmode_width called
warning: [22:08:26.041741][RIGCTRL][debug] () : rig_passband_normal called
warning: [22:08:26.042744][RIGCTRL][debug] () : rig_passband_normal: return filter#6, width=2400
warning: [22:08:26.042744][RIGCTRL][trace] () : newcat_get_mode: returning newcat_get_rx_bandwidth
warning: [22:08:26.043744][RIGCTRL][debug] () : newcat_get_rx_bandwidth called, vfo=VFOA, mode=USB
warning: [22:08:26.043744][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:26.043744][RIGCTRL][trace] () : newcat_valid_command SH
warning: [22:08:26.043744][RIGCTRL][trace] () : newcat_set_vfo_from_alias: alias vfo = VFOA
warning: [22:08:26.044742][RIGCTRL][trace] () : newcat_get_cmd: cache invalidated
warning: [22:08:26.044742][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:26.044742][RIGCTRL][debug] () : serial_flush called
warning: [22:08:26.044742][RIGCTRL][debug] () : tcflush
warning: [22:08:26.045743][RIGCTRL][trace] () : cmd_str = SH0;
warning: [22:08:26.045743][RIGCTRL][debug] () : write_block called
warning: [22:08:26.051747][RIGCTRL][trace] () : write_block(): TX 4 bytes
warning: [22:08:26.051747][RIGCTRL][trace] () : 0000    53 48 30 3b                                         SH0;
warning: [22:08:26.051747][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:26.096778][RIGCTRL][trace] () : read_string(): RX 6 characters
warning: [22:08:26.096778][RIGCTRL][trace] () : 0000    53 48 30 33 30 3b                                   SH030;
warning: [22:08:26.096778][RIGCTRL][trace] () : newcat_get_cmd: read count = 6, ret_data = SH030;
warning: [22:08:26.097778][RIGCTRL][trace] () : newcat_get_rx_bandwidth: w=30
warning: [22:08:26.097778][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:26.097778][RIGCTRL][debug] () : serial_flush called
warning: [22:08:26.097778][RIGCTRL][debug] () : tcflush
warning: [22:08:26.097778][RIGCTRL][trace] () : cmd_str = NA0;
warning: [22:08:26.098779][RIGCTRL][debug] () : write_block called
warning: [22:08:26.105784][RIGCTRL][trace] () : write_block(): TX 4 bytes
warning: [22:08:26.106789][RIGCTRL][trace] () : 0000    4e 41 30 3b                                         NA0;
warning: [22:08:26.107786][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:26.173832][RIGCTRL][trace] () : read_string(): RX 2 characters
warning: [22:08:26.173832][RIGCTRL][trace] () : 0000    3f 3b                                               ?;
warning: [22:08:26.174831][RIGCTRL][trace] () : newcat_get_cmd: read count = 2, ret_data = ?;
warning: [22:08:26.174831][RIGCTRL][error] () : newcat_get_cmd: Command rejected by the rig: 'NA0;'
warning: [22:08:26.175833][RIGCTRL][error] () : get_narrow: unable to parse width from '?;'
warning: [22:08:26.175833][RIGCTRL][trace] () : rig_get_mode: retcode after get_mode=-8
warning: [22:08:26.175833][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:26.176833][RIGCTRL][trace] () : elapsed_ms: after gettime, start = 1610402906,176833200
warning: [22:08:26.243876][RIGCTRL][trace] C:\Users\bill\src\k1jt\wsjtx\Transceiver\HamlibTransceiver.cpp(1012) do_poll: rig_get_mode mode failed with rc: -8 ignoring
and again:

warning: [22:08:28.237219][RIGCTRL][debug] () : rig_get_vfo called
warning: [22:08:28.237219][RIGCTRL][trace] () : elapsed_ms: start = 1610402907,406660200
warning: [22:08:28.238220][RIGCTRL][trace] () : elapsed_ms: elapsed_msecs=832
warning: [22:08:28.238220][RIGCTRL][trace] () : rig_get_vfo: cache check age=831ms
warning: [22:08:28.238220][RIGCTRL][trace] () : rig_get_vfo: cache miss age=831ms
warning: [22:08:28.239221][RIGCTRL][debug] () : newcat_get_vfo called
warning: [22:08:28.239221][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:28.239221][RIGCTRL][trace] () : newcat_valid_command VS
warning: [22:08:28.240222][RIGCTRL][trace] () : newcat_get_vfo: cmd_str = VS;
warning: [22:08:28.240222][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:28.240222][RIGCTRL][debug] () : serial_flush called
warning: [22:08:28.241221][RIGCTRL][debug] () : tcflush
warning: [22:08:28.241221][RIGCTRL][trace] () : cmd_str = VS;
warning: [22:08:28.241221][RIGCTRL][debug] () : write_block called
warning: [22:08:28.248228][RIGCTRL][trace] () : write_block(): TX 3 bytes
warning: [22:08:28.248228][RIGCTRL][trace] () : 0000    56 53 3b                                            VS;
warning: [22:08:28.249228][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:28.282249][RIGCTRL][trace] () : read_string(): RX 4 characters
warning: [22:08:28.282249][RIGCTRL][trace] () : 0000    56 53 30 3b                                         VS0;
warning: [22:08:28.283251][RIGCTRL][trace] () : newcat_get_cmd: read count = 4, ret_data = VS0;
warning: [22:08:28.283251][RIGCTRL][debug] () : newcat_get_vfo_mode called
warning: [22:08:28.283251][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:28.283251][RIGCTRL][trace] () : newcat_valid_command IF
warning: [22:08:28.284251][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:28.284251][RIGCTRL][debug] () : serial_flush called
warning: [22:08:28.284251][RIGCTRL][debug] () : tcflush
warning: [22:08:28.284251][RIGCTRL][trace] () : cmd_str = IF;
warning: [22:08:28.285252][RIGCTRL][debug] () : write_block called
warning: [22:08:28.291255][RIGCTRL][trace] () : write_block(): TX 3 bytes
warning: [22:08:28.291255][RIGCTRL][trace] () : 0000    49 46 3b                                            IF;
warning: [22:08:28.291255][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:28.346293][RIGCTRL][trace] () : read_string(): RX 2 characters
warning: [22:08:28.346293][RIGCTRL][trace] () : 0000    3f 3b                                               ?;
warning: [22:08:28.347294][RIGCTRL][trace] () : newcat_get_cmd: read count = 2, ret_data = ?;
warning: [22:08:28.348294][RIGCTRL][error] () : newcat_get_cmd: Command rejected by the rig: 'IF;'
warning: [22:08:28.348294][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:28.349295][RIGCTRL][trace] () : elapsed_ms: after gettime, start = 1610402908,349295900
warning: [22:08:28.349295][RIGCTRL][error] () : newcat_get_vfo_mode: incorrect length of IF response, expected 27 or 28, got 2
warning: [22:08:28.349295][RIGCTRL][trace] () : elapsed_ms: start = 1610402907,406660200
warning: [22:08:28.349295][RIGCTRL][trace] () : elapsed_ms: elapsed_msecs=10000
warning: [22:08:28.350297][RIGCTRL][error] () : rig_get_vfo: returning -8(Protocol error)
and again:
warning: [22:08:30.831962][RIGCTRL][trace] () : rig_get_cache_timeout_ms: called selection=0
warning: [22:08:30.831962][RIGCTRL][trace] () : rig_set_cache_timeout_ms: called selection=0, ms=0
warning: [22:08:30.832961][RIGCTRL][debug] () : rig_get_freq called vfo=currVFO
warning: [22:08:30.833962][RIGCTRL][trace] () : vfo_fixup: vfo=currVFO
warning: [22:08:30.833962][RIGCTRL][trace] () : vfo_fixup: Leaving currVFO alone
warning: [22:08:30.833962][RIGCTRL][trace] () : get_cache_freq: vfo=currVFO, freq=0
warning: [22:08:30.834963][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:30.834963][RIGCTRL][trace] () : rig_get_freq: cache check age=1000000ms
warning: [22:08:30.835964][RIGCTRL][trace] () : rig_get_freq: cache miss age=1000000ms, cached_vfo=None, asked_vfo=currVFO
warning: [22:08:30.835964][RIGCTRL][debug] () : newcat_get_freq called
warning: [22:08:30.835964][RIGCTRL][trace] () : newcat_get_freq: passed vfo = currVFO
warning: [22:08:30.837967][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:30.838966][RIGCTRL][trace] () : newcat_valid_command FA
warning: [22:08:30.838966][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:30.839967][RIGCTRL][trace] () : newcat_valid_command FB
warning: [22:08:30.839967][RIGCTRL][trace] () : newcat_set_vfo_from_alias: alias vfo = currVFO
warning: [22:08:30.839967][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:30.840968][RIGCTRL][trace] () : newcat_valid_command FA
warning: [22:08:30.840968][RIGCTRL][trace] () : cmd_str = FA;
warning: [22:08:30.840968][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:30.841967][RIGCTRL][debug] () : serial_flush called
warning: [22:08:30.841967][RIGCTRL][debug] () : tcflush
warning: [22:08:30.841967][RIGCTRL][trace] () : cmd_str = FA;
warning: [22:08:31.064118][RIGCTRL][debug] () : write_block called
warning: [22:08:31.070122][RIGCTRL][trace] () : write_block(): TX 3 bytes
warning: [22:08:31.071124][RIGCTRL][trace] () : 0000    46 41 3b                                            FA;
warning: [22:08:31.071124][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:31.127159][RIGCTRL][trace] () : read_string(): RX 2 characters
warning: [22:08:31.128162][RIGCTRL][trace] () : 0000    3f 3b                                               ?;
warning: [22:08:31.128162][RIGCTRL][trace] () : newcat_get_cmd: read count = 2, ret_data = ?;
warning: [22:08:31.128162][RIGCTRL][error] () : newcat_get_cmd: Command rejected by the rig: 'FA;'
warning: [22:08:31.128162][RIGCTRL][trace] () : newcat_get_freq: freq = 0.000000 Hz for vfo VFOA
warning: [22:08:31.128162][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:31.129161][RIGCTRL][trace] () : elapsed_ms: after gettime, start = 1610402911,129161300
warning: [22:08:31.129161][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:31.129161][RIGCTRL][trace] () : elapsed_ms: after gettime, start = 1610402911,129161300
warning: [22:08:31.129161][RIGCTRL][trace] () : rig_get_freq: cache reset age=999000ms, vfo=currVFO, freq=0
warning: [22:08:31.129161][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:31.130161][RIGCTRL][trace] () : elapsed_ms: after gettime, start = 1610402911,130161100
warning: [22:08:31.130161][RIGCTRL][trace] () : rig_set_cache_timeout_ms: called selection=0, ms=500
warning: [22:08:31.130161][RIGCTRL][debug] () : rig_get_vfo called
warning: [22:08:31.130161][RIGCTRL][trace] () : elapsed_ms: start = 1610402910,827958900
warning: [22:08:31.130161][RIGCTRL][trace] () : elapsed_ms: elapsed_msecs=302
warning: [22:08:31.131162][RIGCTRL][trace] () : rig_get_vfo: cache check age=302ms
warning: [22:08:31.131162][RIGCTRL][trace] () : rig_get_vfo: cache hit age=302ms
and again:
warning: [22:08:31.284265][RIGCTRL][debug] () : rig_get_mode called
warning: [22:08:31.285848][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:31.286266][RIGCTRL][trace] () : rig_get_mode: cache check age=1000000ms
warning: [22:08:31.287267][RIGCTRL][trace] () : rig_get_mode: cache miss age=1000000ms
warning: [22:08:31.288268][RIGCTRL][debug] () : newcat_get_mode called
warning: [22:08:31.291270][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:31.292271][RIGCTRL][trace] () : newcat_valid_command MD
warning: [22:08:31.292271][RIGCTRL][trace] () : newcat_set_vfo_from_alias: alias vfo = currVFO
warning: [22:08:31.293272][RIGCTRL][trace] () : newcat_get_mode: cmd_str = MD0;
warning: [22:08:31.293272][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:31.293272][RIGCTRL][debug] () : serial_flush called
warning: [22:08:31.294275][RIGCTRL][debug] () : tcflush
warning: [22:08:31.294275][RIGCTRL][trace] () : cmd_str = MD0;
warning: [22:08:31.295274][RIGCTRL][debug] () : write_block called
warning: [22:08:31.301277][RIGCTRL][trace] () : write_block(): TX 4 bytes
warning: [22:08:31.301277][RIGCTRL][trace] () : 0000    4d 44 30 3b                                         MD0;
warning: [22:08:31.302280][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:31.358314][RIGCTRL][trace] () : read_string(): RX 5 characters
warning: [22:08:31.358314][RIGCTRL][trace] () : 0000    4d 44 30 32 3b                                      MD02;
warning: [22:08:31.359318][RIGCTRL][trace] () : newcat_get_cmd: read count = 5, ret_data = MD02;
warning: [22:08:31.359318][RIGCTRL][debug] () : newcat_rmode_width called
warning: [22:08:31.360316][RIGCTRL][debug] () : rig_passband_normal called
warning: [22:08:31.360316][RIGCTRL][debug] () : rig_passband_normal: return filter#6, width=2400
warning: [22:08:31.360316][RIGCTRL][trace] () : newcat_get_mode: returning newcat_get_rx_bandwidth
warning: [22:08:31.360316][RIGCTRL][debug] () : newcat_get_rx_bandwidth called, vfo=VFOA, mode=USB
warning: [22:08:31.486402][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:31.487402][RIGCTRL][trace] () : newcat_valid_command SH
warning: [22:08:31.487402][RIGCTRL][trace] () : newcat_set_vfo_from_alias: alias vfo = VFOA
warning: [22:08:31.487402][RIGCTRL][trace] () : newcat_get_cmd: cache invalidated
warning: [22:08:31.488403][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:31.488403][RIGCTRL][debug] () : serial_flush called
warning: [22:08:31.488403][RIGCTRL][debug] () : tcflush
warning: [22:08:31.488403][RIGCTRL][trace] () : cmd_str = SH0;
warning: [22:08:31.488403][RIGCTRL][debug] () : write_block called
warning: [22:08:31.495407][RIGCTRL][trace] () : write_block(): TX 4 bytes
warning: [22:08:31.495407][RIGCTRL][trace] () : 0000    53 48 30 3b                                         SH0;
warning: [22:08:31.495407][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:31.540438][RIGCTRL][trace] () : read_string(): RX 6 characters
warning: [22:08:31.540438][RIGCTRL][trace] () : 0000    53 48 30 33 30 3b                                   SH030;
warning: [22:08:31.541440][RIGCTRL][trace] () : newcat_get_cmd: read count = 6, ret_data = SH030;
warning: [22:08:31.541440][RIGCTRL][trace] () : newcat_get_rx_bandwidth: w=30
warning: [22:08:31.541440][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:31.542440][RIGCTRL][debug] () : serial_flush called
warning: [22:08:31.542440][RIGCTRL][debug] () : tcflush
warning: [22:08:31.542440][RIGCTRL][trace] () : cmd_str = NA0;
warning: [22:08:31.542440][RIGCTRL][debug] () : write_block called
warning: [22:08:31.548444][RIGCTRL][trace] () : write_block(): TX 4 bytes
warning: [22:08:31.548444][RIGCTRL][trace] () : 0000    4e 41 30 3b                                         NA0;
warning: [22:08:31.549444][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:31.626496][RIGCTRL][trace] () : read_string(): RX 2 characters
warning: [22:08:31.626496][RIGCTRL][trace] () : 0000    3f 3b                                               ?;
warning: [22:08:31.626496][RIGCTRL][trace] () : newcat_get_cmd: read count = 2, ret_data = ?;
warning: [22:08:31.627497][RIGCTRL][error] () : newcat_get_cmd: Command rejected by the rig: 'NA0;'
warning: [22:08:31.627497][RIGCTRL][error] () : get_narrow: unable to parse width from '?;'
warning: [22:08:31.627497][RIGCTRL][trace] () : rig_get_mode: retcode after get_mode=-8
warning: [22:08:31.627497][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:31.627497][RIGCTRL][trace] () : elapsed_ms: after gettime, start = 1610402911,627497000
and again:
warning: [22:08:33.640852][RIGCTRL][debug] () : rig_get_vfo called
warning: [22:08:33.640852][RIGCTRL][trace] () : elapsed_ms: start = 1610402912,789281100
warning: [22:08:33.640852][RIGCTRL][trace] () : elapsed_ms: elapsed_msecs=852
warning: [22:08:33.641854][RIGCTRL][trace] () : rig_get_vfo: cache check age=851ms
warning: [22:08:33.641854][RIGCTRL][trace] () : rig_get_vfo: cache miss age=851ms
warning: [22:08:33.641854][RIGCTRL][debug] () : newcat_get_vfo called
warning: [22:08:33.641854][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:33.641854][RIGCTRL][trace] () : newcat_valid_command VS
warning: [22:08:33.642853][RIGCTRL][trace] () : newcat_get_vfo: cmd_str = VS;
warning: [22:08:33.642853][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:33.642853][RIGCTRL][debug] () : serial_flush called
warning: [22:08:33.642853][RIGCTRL][debug] () : tcflush
warning: [22:08:33.642853][RIGCTRL][trace] () : cmd_str = VS;
warning: [22:08:33.643854][RIGCTRL][debug] () : write_block called
warning: [22:08:33.649858][RIGCTRL][trace] () : write_block(): TX 3 bytes
warning: [22:08:33.649858][RIGCTRL][trace] () : 0000    56 53 3b                                            VS;
warning: [22:08:33.650858][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:33.727913][RIGCTRL][trace] () : read_string(): RX 4 characters
warning: [22:08:33.728914][RIGCTRL][trace] () : 0000    56 53 30 3b                                         VS0;
warning: [22:08:33.728914][RIGCTRL][trace] () : newcat_get_cmd: read count = 4, ret_data = VS0;
warning: [22:08:33.729911][RIGCTRL][debug] () : newcat_get_vfo_mode called
warning: [22:08:33.729911][RIGCTRL][debug] () : newcat_valid_command called
warning: [22:08:33.729911][RIGCTRL][trace] () : newcat_valid_command IF
warning: [22:08:33.730912][RIGCTRL][trace] () : rig_flush: called for serial device
warning: [22:08:33.730912][RIGCTRL][debug] () : serial_flush called
warning: [22:08:33.730912][RIGCTRL][debug] () : tcflush
warning: [22:08:33.730912][RIGCTRL][trace] () : cmd_str = IF;
warning: [22:08:33.730912][RIGCTRL][debug] () : write_block called
warning: [22:08:33.737917][RIGCTRL][trace] () : write_block(): TX 3 bytes
warning: [22:08:33.737917][RIGCTRL][trace] () : 0000    49 46 3b                                            IF;
warning: [22:08:33.737917][RIGCTRL][trace] () : read_string called, rxmax=129
warning: [22:08:33.792954][RIGCTRL][trace] () : read_string(): RX 2 characters
warning: [22:08:33.792954][RIGCTRL][trace] () : 0000    3f 3b                                               ?;
warning: [22:08:33.793956][RIGCTRL][trace] () : newcat_get_cmd: read count = 2, ret_data = ?;
warning: [22:08:33.793956][RIGCTRL][error] () : newcat_get_cmd: Command rejected by the rig: 'IF;'
warning: [22:08:33.794956][RIGCTRL][trace] () : elapsed_ms: start = 0,0
warning: [22:08:33.794956][RIGCTRL][trace] () : elapsed_ms: after gettime, start = 1610402913,794956900
warning: [22:08:33.794956][RIGCTRL][error] () : newcat_get_vfo_mode: incorrect length of IF response, expected 27 or 28, got 2
warning: [22:08:33.795957][RIGCTRL][trace] () : elapsed_ms: start = 1610402912,789281100
warning: [22:08:33.795957][RIGCTRL][trace] () : elapsed_ms: elapsed_msecs=10000
warning: [22:08:33.795957][RIGCTRL][error] () : rig_get_vfo: returning -8(Protocol error)
More complete log attached.

73
Bill
G4WJS.
On 11/01/2021 10:42, Bill Somerville wrote:

### PR DESCRIPTION
**Pull request by mikaelnousiainen**
This should fix #505 -- the `rc = -RIG_BUSBUSY;` was missing in `newcat_get_cmd`.

### CODE REVIEW

**Comment by mdblack98** [comment]
Nope...still reduces the IF; command for example to only 1 try.
We cannot disable retries on any commands unless we do it by rig model and mode when that model/mode cannot do a command.
What specific rig or rigs does this apply to?

**Comment by mikaelnousiainen** [comment]
@mdblack98 There's still some other bug here -- the flag I introduced should prevent retries only for these very specific commands -- and IF or mode changes are NOT included. The rigs that required this behavior were at least FTDX 5000 and FTDX101. I'm amble to do more testing on FTDX101 today and tomorrow!

**Comment by mdblack98** [comment]
So Yaesu has decided to disable some commands based on mode?  Yuck!!!
No reason shouldn't be able to change MIC gain while in RTTY.  That's the difference between having an analog MIC knob and an encoder knob.  The analog MIC know would work all the time.  The encoder can be set to only allow during certain modes.  
Is there a specific app that is being used?  I know FLRig for example polls for MIC gain but FLRig doesn't complain when things don't work...hamlib does.  We're a little pedantic in hamlib and I'm not inclined to take the "if it don't work ignore it" path.

If the 5000 and 101 can't do it then we code for those rigs and those modes and wait for somebody to complain about other rigs.
Mike W9MDB

 

    On Tuesday, January 12, 2021, 09:17:49 AM CST, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


@mdblack98 There's still some other bug here -- the flag I introduced should prevent retries only for these very specific commands -- and IF or mode changes are NOT included. The rigs that required this behavior were at least FTDX 5000 and FTDX101. I'm amble to do more testing on FTDX101 today and tomorrow!

**Comment by mikaelnousiainen** [comment]
@mdblack98 Yep, these models (at least!) do disable some commands completely in AM/FM modes. Not sure why, it doesn't make any sense. And the response is that ambiguous `?` every time -> retrying causes lots of delays with control, when we should be just ignoring the error.

I can definitely add conditions where the flag is only used with 101 and 5000, but I'm still wondering how this code path gets executed with mode change and IF command. It should not.

**Comment by mikaelnousiainen** [comment]
@mdblack98 Can you post some details on how you're reproducing the issue? I'm still not seeing any possibility with this PR _not_ to retry `?` responses, now that the `rc` variable is set in the loop? Which rig model is in question?

**Comment by mikaelnousiainen** [comment]
@mdblack98 Ok now I can see it finally :D

There are two things I need some clarification about in `newcat_get_cmd`:

1) RIG_BUSBUSY error (which is what I used) leads to command being not re-sent on this line: https://github.com/Hamlib/Hamlib/blob/935b520b441fc9a33b38a126ac633d623c2dbada/rigs/yaesu/newcat.c#L9075 -- what response code should we use with the retries then with `?` response form rig? RIG_ERJCTED possibly (but not return immediately and let the loop handle the retries)?

2) I'm seeing another bug inside the loop here on line 9112, where `rc` variable is not set to any error, so `continue` exits the loop (which I guess should not be the case). If we wish to retry command, `rc` should be set to something else than RIG_BUSBUSY again: https://github.com/Hamlib/Hamlib/blob/935b520b441fc9a33b38a126ac633d623c2dbada/rigs/yaesu/newcat.c#L9112

**Pull request closed without merging**
