### PR TITLE
Complete CTCSS & DCS function mapping

### PR DESCRIPTION
**Pull request by malcolmh**
Map ctcss_tone & ctcss_sql to ctcss_sql
Map dcs_code & dcs_sql to dcs_sql

### CODE REVIEW

**Comment by malcolmh** [comment]
Errors spotted - Back to drawing board!

**Comment by mdblack98** [comment]
Malcolm...you may want to use my fork as it has a rather large patch set on the Icom rigs which may affect what you want to do.
https://github.com/mdblack98/Hamlib


 

    On Tuesday, December 3, 2019, 02:43:05 AM CST, Malcolm Herring <notifications@github.com> wrote:  
 
 
Closed #150.

**Comment by malcolmh** [comment]
Mike, the rig code changes I was doing are trivial & can wait until you merge your changes into the main Hamlib repo.

The bigger issue that brought my work to a halt last year is the need to have backend and rig specific FUNC & PARM definitions. I started a discussion thread on this, but it went quiet before any proposed solutions were tabled. Maybe we should pick this up again after the new release?

**Comment by mdblack98** [comment]
Just fork my repo and work from there....would prefer to see any such changes in the release we hope to get done this month.
https://github.com/mdblack98/Hamlib.git


 

    On Tuesday, December 3, 2019, 08:02:46 AM CST, Malcolm Herring <notifications@github.com> wrote:  
 
 
Mike, the rig code changes I was doing are trivial & can wait until you merge your changes into the main Hamlib repo.

The bigger issue that brought my work to a halt last year is the need to have backend and rig specific FUNC & PARM definitions. I started a discussion thread on this, but it went quiet before any proposed solutions were tabled. Maybe we should pick this up again after the new release?

**Comment by dl7oap** [comment]
_Question Malcolm: There exists two API function for CTCSS tone get/set: ..._ctcss_tone & ...+ctcss_sql. Likewise for DCS code get/set. They have the same arguments & looking at the Icom backend code, do exactly the same.
What is the history here?_

TONE - is only setting the tone when transmit. Receive will be open for all signals.
TSQL - is the tone relevant for transmit and receive. So only signals will come through which have, too, the correct tone. 

this is the technical difference and for icom ic9700 its working correct.
You can set U TONE 1 or U TSQL 1. So i used both option here, sometime i want to here all people, sometimes i want to calm done the receive by only let people through with the correct subtone.

in hamlib there is a small technical difference:
because U TONE 1 sends fe fe a2 00 16 **42** 01 fd
and U TSQL 1 sends fe fe a2 00 16 **43** 01 fd

**Pull request closed without merging**
