### PR TITLE
rigctld thread safe, flrig, and misc

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
regarding tests/amtest.sh, should it be in the source distribution and should it be installed someplace in the file system hierarchy?  Or is it intended for another purpose?

**Comment by mdblack98** [comment]
Meant to test it.  Is there a better place?
Though I do intend to add the perl script testing this is just a simple one.
Mike


 

    On Friday, August 2, 2019, 12:03:48 PM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 
regarding tests/amtest.sh, should it be in the source distribution and should it be installed someplace in the file system hierarchy? Or is it intended for another purpose?

**Comment by N0NB** [comment]
* On 2019 02 Aug 12:10 -0500, Michael Black wrote:
> Meant to test it.  Is there a better place?
> Though I do intend to add the perl script testing this is just a simple one.

Should it be called during the 'make distcheck' or 'make tests' (I
think) phase?

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by N0NB** [comment]
Perhaps during the tests I'd think.  Doesn't do any error checking on it's own though.
Mike 

    On Friday, August 2, 2019, 12:13:45 PM CDT, Nate Bargmann <n0nb@n0nb.us> wrote:  
 
 * On 2019 02 Aug 12:10 -0500, Michael Black wrote:
> Meant to test it.  Is there a better place?
> Though I do intend to add the perl script testing this is just a simple one.

Should it be called during the 'make distcheck' or 'make tests' (I
think) phase?

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by N0NB** [comment]
Applied and pushed.  Sorry for the delay.  Thanks, Mike.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by N0NB** [comment]
Walter,
Please try my fork and let me know that it compiles cleanly for you.I changed the warn/error to pragmas which work here with the LUA/perl bindings
https://github.com/mdblack98/Hamlib

de Mike W9MDB

 

    On Saturday, August 17, 2019, 04:32:12 AM CDT, Walter Fey <notifications@github.com> wrote:  
 
 
@dl8fcl commented on this pull request.

These warnings are breaking the build on openSUSE with lua-binding and python-binding enabled. I have to apply the attached patch.
hamlib-rig.h.diff.txt

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by dl8fcl** [comment]
Hallo Mike,

Your fork compiles cleanly for openSUSE.

73, Walter DL8FCL

Am 18.08.19 um 06:24 schrieb Nate Bargmann:
> Walter,
> Please try my fork and let me know that it compiles cleanly for you.I 
> changed the warn/error to pragmas which work here with the LUA/perl 
> bindings
> https://github.com/mdblack98/Hamlib
>
> de Mike W9MDB
>
>
>
> On Saturday, August 17, 2019, 04:32:12 AM CDT, Walter Fey

**Pull request merged**
