### PR TITLE
 Change RIG_MODE and RIG_FUNC to 64-bit values

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
make distcheck generates this warning:

  CC       testrig.o
../../../tests/testrig.c: In function ‘main’:
../../../tests/testrig.c:404:39: warning: format ‘%i’ expects argument of type ‘int’, but argument 2 has type ‘rmode_t’ {aka ‘long long unsigned int’} [-Wformat=]
         printf("rig_get_mode: mode = %i \n", rmode);
                                      ~^      ~~~~~
                                      %lli

The following quells the warning, so add it to your pull request:

diff --git a/tests/testrig.c b/tests/testrig.c
index 250b7e25..99d8ce8f 100644
--- a/tests/testrig.c
+++ b/tests/testrig.c
@@ -401,7 +401,7 @@ int main(int argc, char *argv[])

     if (retcode == RIG_OK)
     {
-        printf("rig_get_mode: mode = %i \n", rmode);
+        printf("rig_get_mode: mode = %lli \n", rmode);
     }
     else
     {

**Comment by N0NB** [comment]
Building with MinGW for Windows 32:

  CC       netrigctl.lo
netrigctl.c: In function ‘netrigctl_open’:
netrigctl.c:116:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
  ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
  ^
netrigctl.c:116:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:116:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:135:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
  ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
  ^
netrigctl.c:135:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:135:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:156:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
                                 &rs->tuning_steps[i].ts);
                                 ^
netrigctl.c:156:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:156:33: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:170:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
                                 &rs->filters[i].width);
                                 ^
netrigctl.c:170:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:170:33: warning: too many arguments for format [-Wformat-extra-args]

**Comment by N0NB** [comment]
And it looks like the same set of warnings building for Windows 64:

  CC       netrigctl.lo
netrigctl.c: In function ‘netrigctl_open’:
netrigctl.c:116:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
  ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
  ^
netrigctl.c:116:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:116:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:135:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
  ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
  ^
netrigctl.c:135:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:135:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:156:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
                                 &rs->tuning_steps[i].ts);
                                 ^
netrigctl.c:156:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:156:33: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:170:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
                                 &rs->filters[i].width);
                                 ^
netrigctl.c:170:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:170:33: warning: too many arguments for format [-Wformat-extra-args]


Fortunately, no other warnings seen.  This is an old MinGW version running on Debian Jessie (version 8).

**Comment by mdblack98** [comment]
Yup...gotta' change those too.  Compiled OK on Linux 64-bit.
I'll have these changes by tomorrow morning after some compilation testing on Windows (so blasted slow on Windows with mingw single-threading).
Mike
 

    On Friday, December 21, 2018, 8:12:54 PM CST, Nate Bargmann <notifications@github.com> wrote:  
 
 
And it looks like the same set of warnings building for Windows 64:

CC netrigctl.lo
netrigctl.c: In function ‘netrigctl_open’:
netrigctl.c:116:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
^
netrigctl.c:116:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:116:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:135:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
^
netrigctl.c:135:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:135:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:156:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
&rs->tuning_steps[i].ts);
^
netrigctl.c:156:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:156:33: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:170:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
&rs->filters[i].width);
^
netrigctl.c:170:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:170:33: warning: too many arguments for format [-Wformat-extra-args]

Fortunately, no other warnings seen. This is an old MinGW version running on Debian Jessie (version 8).

**Comment by mdblack98** [comment]
Looks clean on Win32 mingw now.  This should now be portable across any compiler just as the previous hamlib was.  Just had to change all the mode and func references to the proper, portable, 64-bit versions.
WSJT-X works both through the direct connection and via rigctld and does use the mode calls...but not the func calls.
The ABI is broken as of this commit since the size of these objects has now changed.
de Mike W9MDB

 

    On Friday, December 21, 2018, 8:12:54 PM CST, Nate Bargmann <notifications@github.com> wrote:  
 
 
And it looks like the same set of warnings building for Windows 64:

CC netrigctl.lo
netrigctl.c: In function ‘netrigctl_open’:
netrigctl.c:116:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
^
netrigctl.c:116:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:116:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:135:2: warning: unknown conversion type character ‘l’ in format [-Wformat=]
ret = num_sscanf(buf, "%"SCNfreq"%"SCNfreq"%llx%d%d%x%x",
^
netrigctl.c:135:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:135:2: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:156:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
&rs->tuning_steps[i].ts);
^
netrigctl.c:156:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:156:33: warning: too many arguments for format [-Wformat-extra-args]
netrigctl.c:170:33: warning: unknown conversion type character ‘l’ in format [-Wformat=]
&rs->filters[i].width);
^
netrigctl.c:170:33: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 3 has type ‘rmode_t *’ [-Wformat=]
netrigctl.c:170:33: warning: too many arguments for format [-Wformat-extra-args]

Fortunately, no other warnings seen. This is an old MinGW version running on Debian Jessie (version 8).

**Comment by N0NB** [comment]
Broken ABI is fine as we're already there!

**Comment by N0NB** [comment]
Hi Mike.                                                                                                                            
                                                                                                                                    
I've tested up to your latests commits and it all compiled clean on                                                                 
Debian Buster and with MinGW on Debian Jessie both 32 and 64 bit                                                                    
runs. I'll merge it upon your OK.                                                                                                   
                                                                                                                                    
73, Nate

**Comment by N0NB** [comment]
Applied and pushed.  Thanks, Mike.

**Pull request merged**
