### PR TITLE
Add split freq control to Kenwood TMD710

### PR DESCRIPTION
**Pull request by RhinoLance**
Add TM710_(get|set)_split_freq functions.

This allows programs like GPredict to control both sides of the radio by emulating split frequency capability.

### CODE REVIEW

**Comment by mdblack98** [comment]
You added .two files that don't belong in the commit.

I also had to modify the tmd710.c to work with the current code base.

Please do a clone of the current codebase and let me know that it works OK.

If so you can close your pull request.

Mike W9MDB










On Monday, June 20, 2022, 01:28:09 AM CDT, Lance Conry ***@***.***> wrote: 





Add TM710_(get|set)_split_freq functions.

This allows programs like GPredict to control both sides of the radio by emulating split frequency capability.

________________________________

You can view, comment on, or merge this pull request online at:

  https://github.com/Hamlib/Hamlib/pull/1071

Commit Summary

     
    * 63aa369 Added tm710_(get|set)_split_freq functions
    
    * b59e803 Forgot to add definitions.
    
    * 52176e5 Tried different way to toggle split VFO variable
    
    * e685b6c debug
    
    * 6bd2302 debug
    
    * a3241e2 debug
    
    * cbef1e0 Whoops, bad var type for printf
    
    * 420febb debug
    
    * 4529ef0 debug
    
    * ce99084 debug
    
    * d92f8d8 debug
    
    * daa2427 debug
    
    * 15c0f2b debug
    
    * 50b1f7f debug
    
    * 65711d0 trying with setting the tx_VFO to manage which way the split works whilst having safe defaults
    
    * 4ac93f9 debug
    
    * 35b18ee syntax
    
    * 29970b8 syntax
    
    * c12d393 debug
    
    * d470059 debug
    
    * b2c5ecc debug
    
    * acd57e6 debug
    
    * d06d102 debug
    
    * d44c241 debug
    
    * bb7a770 debug
    
    * 0bcf55f debug
    
    * 4dbbf90 debug
    
    * db6321e debug
    
    * 7560c31 debug
    
    * 09740cc debug
    
    * be7a526 debug
    
    * 4621193 savepoint
    
    * 1a9903a cleanup
    
File Changes  (3 files) 
     
    *  M .gitignore (111) 
    
    *  M kenwood/tmd710.c (146) 
    
    *  A winradio/linradio/.dirstamp (0) 
    

Patch Links:

     
    * https://github.com/Hamlib/Hamlib/pull/1071.patch
    
    * https://github.com/Hamlib/Hamlib/pull/1071.diff

**Comment by RhinoLance** [comment]
Thanks Mike,

I've just tested and it is all working well so will close the PR.  A couple of things to note (no idea if it's related to this PR though):

1.  At build, the following warning is displayed:
```
tmd710.c: In function ‘tmd710_set_mode’:
tmd710.c:1477:18: warning: ‘tmd710_mode’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   fo_struct.mode = tmd710_mode;
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
```

2.  When the connection to rigctld closes, it prints the old rig model (234 instead of 2034).  This change to a four digit rigId happened between my edit and the pull request, so don't know if it's an artefact of merging old code with new, or unrelated.
`Closed rig model 234, 'TM-D710(G) - no clients, will reopen for new clients'`

**Comment by mikaelnousiainen** [comment]
@RhinoLance @mdblack98 This breaks current functionality for non-split operation. The frequency shows the opposite VFO frequency always. There is no way to enable/disable the functionality.

**Comment by RhinoLance** [comment]
@mdblack98 in doing some more testing last night, there is something screwy going on with the update ported to the new codebase.  In certain circumstances the control and ptt erratically bounces between VFOs.  I'm in the process of trying to identify what is causing it, as it doesn't always happen.

@mikaelnousiainen just to clarify, what commands are you issuing that is showing the wrong behaviour?

**Comment by mdblack98** [comment]
WSJT-X?

Please place this file as described below
https://www.dropbox.com/s/t52ngcalsgnpm8m/wsjtx_log_config.ini?dl=0


    C:\Users\[username]\AppData\Local\WSJT-X
    The WSJT-X_Rigcontrol.log file will be in the same location
    
For Linux put it in  
    ~/.config
    The WSJT-X_Rigcontrol.log file will be here:
    ~/.local/share/WSJT-X
    
Restart WSJT-X and duplicate the problem.
Shut down WSJT-X


Then send me the WSJT-X_RigControl.log file
Mike W9MDB








On Tuesday, June 21, 2022, 04:29:32 PM CDT, Lance Conry ***@***.***> wrote: 







@mdblack98 in doing some more testing last night, there is something screwy going on with the update ported to the new codebase. In certain circumstances the control and ptt erratically bounces between VFOs. I'm in the process of trying to identify what is causing it, as it doesn't always happen.

@mikaelnousiainen just to clarify, what commands are you issuing that is showing the wrong behaviour?

**Comment by RhinoLance** [comment]
@mdblack98 No, Gpredict

**Comment by RhinoLance** [comment]
@mdblack98 I discovered the cause of the bouncing CTRL + PTT.

At the moment, the rig_caps of TMD710.c has:
`.targetable_vfo =  RIG_TARGETABLE_NONE,`
but should be:
`.targetable_vfo = RIG_TARGETABLE_FREQ,`

As I understand it, this specifies that the rig can get/set frequencies without needing to set control to that VFO.

Because of this, every time a different VFO is operated on (to get/set frequency etc),  eg. rig_(get|set)_freq (rig.c) calls set_vfo, which sets the CTRL+ PTT to the target VFO.  This is unnecessary as these rigs don't need control to operate on the frequencies.

**Comment by mdblack98** [comment]
Done.

I don't suppose it has targetable mode too?

Is there a manual that shows the CAT protocol for this thing?

Mike W9MDB








On Friday, June 24, 2022 at 02:06:38 AM CDT, Lance Conry ***@***.***> wrote: 







@mdblack98 I discovered the cause of the bouncing CTRL + PTT.

At the moment, the rig_caps of TMD710.c has:
.targetable_vfo = RIG_TARGETABLE_NONE,
but should be:
.targetable_vfo = RIG_TARGETABLE_FREQ,

As I understand it, this specifies that the rig can get/set frequencies without needing to set control to that VFO.

Because of this, every time a different VFO is operated on (to get/set frequency etc), eg. rig_(get|set)_freq (rig.c) calls set_vfo, which sets the CTRL+ PTT to the target VFO. This is unnecessary as these rigs don't need control to operate on the frequencies.

**Comment by RhinoLance** [comment]
Yes, it does mode too.

The best protocol reference to develop against is https://github.com/LA3QMA/TM-V71_TM-D710-Kenwood/

**Comment by mdblack98** [comment]
I added TARGETABLE_MODE as that should be working for this rig too.

 

    On Sunday, June 26, 2022 at 04:44:35 PM CDT, Lance Conry ***@***.***> wrote:  
 
 


Yes, it does mode too.

The best protocol reference to develop against is https://github.com/LA3QMA/TM-V71_TM-D710-Kenwood/

**Pull request closed without merging**
