### PR TITLE
Add PKTFM PKTAM for ic7300

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
At lines 212-214 you have:
 		{RIG_MODE_AM|RIG_MODE_PKTFM, kHz(6)},

Did you mean RIG_MODE_PKTAM here?

**Comment by mdblack98** [comment]
Oops...yup.  Good catch.  THe PKT mode widths are the same as the base mode widths for these.
Mike

 

    On Thursday, May 3, 2018, 7:39:40 AM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 
At lines 212-214 you have:
{RIG_MODE_AM|RIG_MODE_PKTFM, kHz(6)},

Did you mean RIG_MODE_PKTAM here?

**Comment by N0NB** [comment]
* On 2018 03 May 07:46 -0500, mdblack98 wrote:
> Oops...yup.  Good catch.  THe PKT mode widths are the same as the base
> mode widths for these.

Do you want me to fix it after I pull it?  It's easy enough.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by mdblack98** [comment]
Go ahead....


 

    On Thursday, May 3, 2018, 11:36:15 AM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 * On 2018 03 May 07:46 -0500, mdblack98 wrote:
> Oops...yup.  Good catch.  THe PKT mode widths are the same as the base
> mode widths for these.

Do you want me to fix it after I pull it? It's easy enough.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds. The pessimist fears this is true."

Web: http://www.n0nb.us GPG key: D55A8819 GitHub: N0NB

**Comment by mdblack98** [comment]
I updated it already

**Comment by N0NB** [comment]
* On 2018 04 May 10:47 -0500, mdblack98 wrote:
> I updated it already

I see that.  Thanks.

I'm busy getting cattle out to pasture so I'll pull it tonight.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Pull request merged**
