### PR TITLE
Implement new Icom custom parms & levels method for rigs that use them

### PR DESCRIPTION
**Pull request by malcolmh**
The lookup table method for specifying custom parms has been implemented for the rigs 7300/9700, 7600 & 756. The old g/set_custom_parm functions in icom.c, being redundant, are now deleted.

### CODE REVIEW

**Comment by N0NB** [comment]
Why is get/set powerstat removed from all those rigs?  It was specifically tested on the ic7300 and worked fine and is designed to (hopefully) work on all Icom rigs...or fail gracefully.
I'd rather improve it then remove it if it's causing problems.  Worked OK on ic7300 and ic706MKIIG in my testing (and several other Icom rigs)
There some future improvements that depend on all Icom rigs having a common capability (at least honored in hamlib if not the rig itself).
de Mike W9MDB

 

    On Tuesday, January 21, 2020, 04:52:34 AM CST, Malcolm Herring <notifications@github.com> wrote:  
 
 
The lookup table method for specifying custom parms has been implemented for the rigs 7300/9700, 7600 & 756. The old g/set_custom_parm functions in icom.c, being redundant, are now deleted.

You can view, comment on, or merge this pull request online at:

  https://github.com/Hamlib/Hamlib/pull/184

Commit Summary
   
   - correct powerstat caps
   - Merge remote-tracking branch 'Hamlib/master'
   - New custom parm implementations

File Changes
   
   -  M rigs/icom/ic7100.c (1) 
   -  M rigs/icom/ic7300.c (197) 
   -  M rigs/icom/ic756.c (139) 
   -  M rigs/icom/ic7600.c (156) 
   -  M rigs/icom/icom.c (63) 
   -  M rigs/icom/icr8600.c (2) 
   -  M rigs/icom/id51.c (3) 

Patch Links:
   
   - https://github.com/Hamlib/Hamlib/pull/184.patch
   - https://github.com/Hamlib/Hamlib/pull/184.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 _______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by malcolmh** [comment]
I removed the get_powerstats as these don't exist for Icom rigs. Command 0x18 is only a set operation. This I confirmed before deleting by attempting a get_powerstat for my rigs & got 0xfa response.

**Comment by N0NB** [comment]
I know they don't have the command -- it's harmless.  Unless it's causing an error or some other problem please don't remove them.  It's a first step towards other capabilities....


de Mike W9MDB

 

    On Tuesday, January 21, 2020, 08:23:36 AM CST, Malcolm Herring <notifications@github.com> wrote:  
 
 
I removed the get_powerstats as these don't exist for Icom rigs. Command 0x18 is only a set operation. This I confirmed before deleting by attempting a get_powerstat for my rigs & got 0xfa response.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe._______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by malcolmh** [comment]
OK, restored

**Comment by N0NB** [comment]
Guys, rather than this commit ping-pong of removing something and then putting it back, I would prefer that the originator close the PR, rebase in their local working tree to factor out the delete and restore commits, and then issue a new PR.

Thanks.

- Nate

**Pull request merged**
