### PR TITLE
Fixed c++ exception for visual studio compiler

### PR DESCRIPTION
**Pull request by BigNerd95**

### CODE REVIEW

**Comment by gvanem** [comment]
Since when was Visual Studio supported in Hamlib?

**Comment by mdblack98** [comment]
Somebody was able to build it...not directly supported with any solution file or VS project file.
Mike W9MDB

 

    On Sunday, August 1, 2021, 01:22:27 PM CDT, Gisle Vanem ***@***.***> wrote:  
 
 


Since when was Visual Studio supported in Hamlib?

**Comment by BigNerd95** [comment]
In precompiled DLLs there is no C++ bindings, so to use these precompiled DLLs I need to compile rigclass (and others) with visual studio

**Comment by gvanem** [comment]
@BigNerd95 Are you sure it's safe to throw from a MinGW-build .dll to a Visual Studio program using it?

**Comment by wsxarcher** [comment]
The precompiled C dll can be used from anywhere because C is ABI stable, that's why Hamlib releases contains only the C part. C++ is not, so as you said, it's NOT possible to throw an exception from MINGW binary and be catched by a MSVC binary. Therefore you need to compile the C++ wrapper together with your project with the same C++ compiler, so this patch was needed.

**Comment by gvanem** [comment]
This little test works fine for MSVC/clang-cl. But with MinGW it crashes and WinDbg kicks in:
```c++
#include <hamlib/rigclass.h>
#include <hamlib/ampclass.h>

int main (void)
{
#ifdef __MINGW32__
  puts ("Hello from MinGW's 'main()'");
#else
  puts ("Hello from MSVC's 'main()'");
#endif

  Amplifier *a = nullptr;

  try {
    a = new Amplifier (100);  // > AMP_BACKEND_MAX
  }
  catch (const RigException &Ex) {
    puts (Ex.message);
  }

  if (a)
    delete a;
  return (0);
}
```
Output:
```
Hello from MinGW's 'main()'
amp_init called
amp_check_backend: unsupported backend 1 for model 100
terminate called after throwing an instance of 'RigException'
```

The `catch()` is not called! Some issue with exceptions in MinGW?
Call-stack:
```
ntdll!NtTerminateProcess+0xc
ntdll!RtlExitUserProcess+0xbd
KERNEL32!ExitProcessImplementation+0x12
msvcrt!__crtExitProcess+0x17
msvcrt!doexit+0x135
msvcrt!_exit+0x11
msvcrt!abort+0xe8
libstdc___6!ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x1a6
throw_test!std::ios_base::good+0xa
throw_test!std::basic_ostream<char,std::char_traits<char> >::sentry::sentry(class std::basic_ostream<char,std::char_traits<char> > * _Ostr = 0x013ffb98)+0x76
KERNEL32!BaseThreadInitThunk+0x19
ntdll!__RtlUserThreadStart+0x2f
ntdll!_RtlUserThreadStart+0x1b
```

**Comment by mdblack98** [comment]
See if this helps...MinGw is crippled apparently.
http://mingw.5.n7.nabble.com/How-to-use-try-catch-exception-in-MinGw-td8212.html
https://en.cppreference.com/w/cpp/memory/new/set_new_handler

Mike W9MDB 

    On Tuesday, August 3, 2021, 09:28:43 AM CDT, Gisle Vanem ***@***.***> wrote:  
 
 


This little test works fine for MSVC/clang-cl. But with MinGW it crashes and WinDbg kicks in:
#include <hamlib/rigclass.h>
#include <hamlib/ampclass.h>

int main (void)
{
#ifdef __MINGW32__
  puts ("Hello from MinGW's 'main()'");
#else
  puts ("Hello from MSVC's 'main()'");
#endif

  Amplifier *a = nullptr;

  try {
    a = new Amplifier (100);  // > AMP_BACKEND_MAX
  }
  catch (const RigException &Ex) {
    puts (Ex.message);
  }

  if (a)
    delete a;
  return (0);
}
Output:
Hello from MinGW's 'main()'
amp_init called
amp_check_backend: unsupported backend 1 for model 100
terminate called after throwing an instance of 'RigException'

The catch() is not called! Some issue with exceptions in MinGW?
Call-stack:
ntdll!NtTerminateProcess+0xc
ntdll!RtlExitUserProcess+0xbd
KERNEL32!ExitProcessImplementation+0x12
msvcrt!__crtExitProcess+0x17
msvcrt!doexit+0x135
msvcrt!_exit+0x11
msvcrt!abort+0xe8
libstdc___6!ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x1a6
throw_test!std::ios_base::good+0xa
throw_test!std::basic_ostream<char,std::char_traits<char> >::sentry::sentry(class std::basic_ostream<char,std::char_traits<char> > * _Ostr = 0x013ffb98)+0x76
KERNEL32!BaseThreadInitThunk+0x19
ntdll!__RtlUserThreadStart+0x2f
ntdll!_RtlUserThreadStart+0x1b

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
