### PR TITLE
Enable optional generation of the PDF manual

### PR DESCRIPTION
**Pull request by N0NB**
In the event anyone wants a PDF version of the reference manual, it can
be generated now.

### CODE REVIEW

**Comment by w4jkl** [comment]
Nate,

I edited hamlib.cfg.in to turn on latex, then ran make doc.

***@***.***:~/Downloads/Hamlib-master/doc$ sudo nano hamlib.cfg.in
***@***.***:~/Downloads/Hamlib-master/doc$ make doc
for script in build-w32.sh build-w64.sh ; \
   do \
     source-highlight -n -f html -i ../scripts/${script} -o 
../scripts/${script}.html ; \
     source-highlight -n -f latex -i ../scripts/${script} -o 
../scripts/${script}.tex ; \
   done
/bin/bash: line 2: source-highlight: command not found
/bin/bash: line 3: source-highlight: command not found
/bin/bash: line 2: source-highlight: command not found
/bin/bash: line 3: source-highlight: command not found
make: *** [Makefile:680: doc] Error 127
***@***.***:~/Downloads/Hamlib-master/doc$

No joy here, Nate. Any ideas about what I'm doing wrong?

John W4JKL

**Comment by w4jkl** [comment]
Sorry, left off part of it.

***@***.***:~/Downloads/Hamlib-master/doc$ sudo nano hamlib.cfg.in
***@***.***:~/Downloads/Hamlib-master/doc$ cd latex
-bash: cd: latex: No such file or directory
***@***.***:~/Downloads/Hamlib-master/doc$ make
make: Nothing to be done for 'all'.
***@***.***:~/Downloads/Hamlib-master/doc$

**Comment by w4jkl** [comment]
Works. All of source-highlight's dependencies were not installed for 
some reason.

Sorry for the noise.

73,

John W4JKL

**Comment by N0NB** [comment]
* On 2021 18 May 13:16 -0500, w4jkl wrote:
> Works. All of source-highlight's dependencies were not installed for 
> some reason.
> 
> Sorry for the noise.

That's okay, John.

Sometimes Mr. Murphy sticks his grubby fingers in our systems!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by N0NB** [comment]
BTW, Thanks for jumping in and giving this a try!  I wasn't expecting that.

73, Nate

**Pull request merged**
