### PR TITLE
Kenwood TH-D74

### PR DESCRIPTION
**Pull request by denzs**
this is a quite early version of a new model...

it is mainly copy n paste artwork from thd72.c and th.c mixed with the information from https://github.com/LA3QMA/TH-D74-Kenwood/

i removed the static from kenwood_wrong_vfo to make i available in thd74.c too.
there is propably a better way to do that?!

any feedback and/or testing would be appreciated :)

### CODE REVIEW

**Comment by bagel99** [comment]
I have been working on the thd72 driver, since the master version doesn't work.  You can see my work in bagel99/Hamlib/kenwood/thd72.c.  Perhaps the d72 and d74 have a lot in common?

**Comment by N0NB** [comment]
Hi Sebastian.

* On 2018 01 May 07:15 -0500, Sebastian Denz wrote:
> this is a quite early version of a new model...

Thanks for getting involved.

> it is mainly copy n paste artwork from thd72.c and th.c mixed with the information from https://github.com/LA3QMA/TH-D74-Kenwood/
> 
> i removed the static from kenwood_wrong_vfo to make i available in thd74.c too.
> there is propably a better way to do that?!
> 
> any feedback and/or testing would be appreciated :)
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Hamlib/Hamlib/pull/19
> 
> -- Commit Summary --
> 
>   * add RIG_MODE_DR as D-Star

Should this be more broadly applied than just D-Star?  Undoubtedly, in
the future we're going to have others that use DMR, P25, and other
protocols not yet on the drawing board.  Or will we need a macro for
each of those modes?

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by denzs** [comment]
Hi Nate,

thanks for your feedback!
It is really inspiring to see the rig getting to work with hamlib :)

I am not sure, which way to go regarding the need for the new digital modes..

Regarding the Kenwood (i should mention, i havent used DStar at all til now) it would make sense to be able to distinguish between D-Star-Voice and D-Star-Repeater...
But i understand that this approach could result in a lot of new modes introduced in the future.

As an alternative one could add just a generic digital mode, but then it would propably not be possible to choose between them via a frontend application (or the application itself has to add some logic regarding the specific rig) in a comfortable way.

So at the moment i think this should be solved in hamlib, propably by adding the modes in a seperate fashion?!

@bagel99
Thanks for your feedback too!
Your approach looks very promising and cleaner than my quick n dirty implementation and i really like your way of using the VFO channel information, i will test your code with the THD74 to see what we could use in common! :)

73, Sebastian

**Comment by N0NB** [comment]
* On 2018 02 May 02:01 -0500, Sebastian Denz wrote:
> Hi Nate,
> 
> thanks for your feedback!
> It is really inspiring to see the rig getting to work with hamlib :)

Yes, it is.  :-)

> I am not sure, which way to go regarding the need for the new digital modes..
> 
> Regarding the Kenwood (i should mention, i havent used DStar at all
> til now) it would make sense to be able to distinguish between
> D-Star-Voice and D-Star-Repeater...  But i understand that this
> approach could result in a lot of new modes introduced in the future.

Indeed.  At the moment, there are 23 modes defined in rig.h.  There are
no digital voice modes defined at present.  The modes are defined in an
enum which, is limited to 31 entries, as I recall, so there would only
be room for eight more mode entries.  Clearly not enough!

> As an alternative one could add just a generic digital mode, but then
> it would propably not be possible to choose between them via a
> frontend application (or the application itself has to add some logic
> regarding the specific rig) in a comfortable way.

As I see it, future radios will probably support the setting of DV modes
in a manner similar to analog radios setting AM, LSB, USB, etc.

> So at the moment i think this should be solved in hamlib, propably by
> adding the modes in a seperate fashion?!

Should this be done through a new set of functions such as
rig_[set|get]_dvmode() and then a new data structure devoted solely to
digital voice modes?

I am going to CC the mailing list, so hopefully we'll get some other
feedback there.

> @bagel99
> Thanks for your feedback too!
> Your approach looks very promising and cleaner than my quick n dirty
> implementation and i really like your way of using the VFO channel
> information, i will test your code with the THD74 to see what we could
> use in common! :)

I hope both of you can collaborate on this!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by bagel99** [comment]
It appears there is little in common between the TH-D72 and TH-D74 protocols.  I guess consistency is not a virtue for Kenwood.

**Comment by denzs** [comment]
@bagel99 you're right... consistencty doesnt seem to be on their agenda at all..
At least the THD74 is missing the MU command which seems to be quite handy, and the structure from FO differs a lot...
Another open point is detecting the ptt-state... i already mailed Kenwood on that.

But anyhow, i will propably use your code as boilerplate for the THD74. :)

@Nate
As the discussion about how to add the new digital modes seems to be running at the moment i
would ignore that at least for now, and keep on watching the disussion?!

**Comment by N0NB** [comment]
* On 2018 05 May 17:20 -0500, Black Michael via Hamlib-developer wrote:

Reformatting for readability...

--------------------8<------------------

#include <stdio.h>

enum small_enum {
    a
};

enum large_enum {
    b = 0x7FFFFFFFFFFFFFFF // 2^63-1
};

int main()
{

#ifdef __LP64__
    printf("LP64: %ld %ld %d %lx\n",
           sizeof(enum small_enum),
           sizeof(enum large_enum),
           a,
           b);
#else
    printf("%d %d %d %llx\n",
           sizeof(enum small_enum),
           sizeof(enum large_enum),
           a,
           b);
#endif

    return 0;
}

-------------------->8------------------


I added a bit of text so I could tell the difference.  On Slackware64
14.2 I get:

$ ./lp64
LP64: 4 8 0 7fffffffffffffff

and in the Slackware 14.2 (32 bit VM) I get:

$ ./lp64 
4 8 0 7fffffffffffffff
 
Since the modes are defined as bitmask values and are ORed together in
the rig_caps structure, as I see it, using 64 bit enums only doubles our
present mode space to 63.  As changing this is an ABI/API change, I
think we should future proof this as much as possible.  IMO, the maximum
number of modes should be at a minimum 1024 or unlimited.  SDRs will
likely support all the variations of digi data/voice modes as individual
"modes", so this needs to be a large namespace.

Likewise, the number of "VFOs" and antenna ports need to be
large/unlimited.  How imaginative will split frequency operations
become?

Time to dust off the crystal balls and throw some ideas around.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by mdblack98** [comment]
Try this patch out for size...compiles 64/32 bit and MinGW 32-bit (still uses 64-bit enums).One define RMODE64 enables it...could be a configure option to turn it on.I added some extra modes for fun and also put them in TRXManager since that's one that I know uses them.
So still backwards compatible and forwards compatible until we break the API completely by user choice.  I'm running this with WSJT-X right now and it works fine with 64-bit enums since hamlib is built-in.You'll see the message telling you how it's compiling....64/64 or 64/32
https://www.dropbox.com/s/jm69jthxe3nvq61/mode64.patch?dl=1

de Mike W9MDB

 

    On Saturday, May 12, 2018, 7:42:15 AM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 * On 2018 05 May 17:20 -0500, Black Michael via Hamlib-developer wrote:

Reformatting for readability...

--------------------8<------------------

#include <stdio.h>

enum small_enum {
 a
};

enum large_enum {
 b = 0x7FFFFFFFFFFFFFFF // 2^63-1
};

int main()
{

#ifdef __LP64__
 printf("LP64: %ld %ld %d %lx\n",
 sizeof(enum small_enum),
 sizeof(enum large_enum),
 a,
 b);
#else
 printf("%d %d %d %llx\n",
 sizeof(enum small_enum),
 sizeof(enum large_enum),
 a,
 b);
#endif

 return 0;
}

-------------------->8------------------


I added a bit of text so I could tell the difference. On Slackware64
14.2 I get:

$ ./lp64
LP64: 4 8 0 7fffffffffffffff

and in the Slackware 14.2 (32 bit VM) I get:

$ ./lp64 
4 8 0 7fffffffffffffff
 
Since the modes are defined as bitmask values and are ORed together in
the rig_caps structure, as I see it, using 64 bit enums only doubles our
present mode space to 63. As changing this is an ABI/API change, I
think we should future proof this as much as possible. IMO, the maximum
number of modes should be at a minimum 1024 or unlimited. SDRs will
likely support all the variations of digi data/voice modes as individual
"modes", so this needs to be a large namespace.

Likewise, the number of "VFOs" and antenna ports need to be
large/unlimited. How imaginative will split frequency operations
become?

Time to dust off the crystal balls and throw some ideas around.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds. The pessimist fears this is true."

Web: http://www.n0nb.us GPG key: D55A8819 GitHub: N0NB

**Comment by denzs** [comment]
@mdblack thanks for the patch, looks fine to me for the moment?!

@Nate what do you think?

**Comment by N0NB** [comment]
No problem on holding off.  I still would to see what we could figure out for more than 63 modes for the future.

**Comment by mdblack98** [comment]
I think the 63-mode patch when tested enough is a good thing for 3.1 or 3.2.
I can't think of how to go bigger than that without having an awful lot of rewrites on the backends.
Boolean ops will be difficult or impossible. 
I was thinking bit 63 could be for "extended" modes but can't see how to marry that to the boolean ops.
MIke
 

    On Thursday, May 17, 2018, 6:38:01 PM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 
No problem on holding off. I still would to see what we could figure out for more than 63 modes for the future.

**Comment by nate** [comment]
@denzs: I think you mean @N0NB and not @nate

**Comment by denzs** [comment]
Any new thoughts on this?

As WSJT-X 1.9.x has been released and the ABI seems to progress i would love to get the support for the THD74 into hamlib...

I think delaying the option to set the digital modes could be an alternative too?!

**Comment by mdblack98** [comment]
Why don't you added it to 3.X without the additional modes and then add the modes to 4.X
de Mike W9MDB


 

    On Wednesday, August 8, 2018, 4:35:58 AM CDT, Sebastian Denz <notifications@github.com> wrote:  
 
 
Any new thoughts on this?

As WSJT-X 1.9.x has been released and the ABI seems to progress i would love to get the support for the THD74 into hamlib...

I think delaying the option to set the digital modes could be an alternative too?!

**Comment by denzs** [comment]
Just to let you know, i'll try to have a mergeable version without the support for digital modes in the next days...

**Comment by N0NB** [comment]
* On 2018 20 Nov 00:46 -0600, Sebastian Denz wrote:
> Just to let you know, i'll try to have a mergeable version without the
> support for digital modes in the next days...

That works for me.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by denzs** [comment]
The USB issue did not occur since the ptt fix on my machine, so i think this could be a version which would be worth to be merged :)

**Comment by MichaelRenner** [comment]
Moin, I checked some commands via rigctrl with success:
* Switch from VFO A to VFO B and back
* set and release PTT
* read and set VFO frequencies
* read and set Memory channels
* read and set mode (AM, USB. LSB, USB, CW)
* get_info (of cause)
CU

**Comment by denzs** [comment]
If there is anything wrong with the contribution i would be happy to know and get it fixed...

**Comment by denzs** [comment]
@N0NB i would be glad to get this merged or to get some feedback ;)

**Comment by N0NB** [comment]
* On 2019 21 Jan 01:32 -0600, Sebastian Denz wrote:
> @N0NB i would be glad to get this merged or to get some feedback ;)
> 

Great!  I was thinking of asking if this was ready.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by N0NB** [comment]
Hi Denz.

I am seeing the following warnings from GCC 8 on Debian Buster:

  CC       thd74.lo
../../hamlib/kenwood/thd74.c: In function ‘thd74_set_split_freq’:
../../hamlib/kenwood/thd74.c:1408:23: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
         sprintf(fbuf, "%010"PRIll, (int64_t)tx_freq);
                       ^~~~~~
In file included from ../../hamlib/include/hamlib/rig.h:29,
                 from ../../hamlib/kenwood/thd74.c:30:
/usr/include/inttypes.h:57:35: note: format string is defined here
 # define PRId64  __PRI64_PREFIX "d"
                                   ^
../../hamlib/kenwood/thd74.c:1408:9: note: ‘sprintf’ output between 11 and 12 bytes into a destination of size 11
         sprintf(fbuf, "%010"PRIll, (int64_t)tx_freq);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../hamlib/kenwood/thd74.c: In function ‘thd74_set_freq’:
../../hamlib/kenwood/thd74.c:417:19: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
     sprintf(fbuf, "%010"PRIll, (int64_t)freq);
                   ^~~~~~
In file included from ../../hamlib/include/hamlib/rig.h:29,
                 from ../../hamlib/kenwood/thd74.c:30:
/usr/include/inttypes.h:57:35: note: format string is defined here
 # define PRId64  __PRI64_PREFIX "d"
                                   ^
../../hamlib/kenwood/thd74.c:417:5: note: ‘sprintf’ output between 11 and 12 bytes into a destination of size 11
     sprintf(fbuf, "%010"PRIll, (int64_t)freq);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../hamlib/kenwood/thd74.c: In function ‘thd74_set_level’:
../../hamlib/kenwood/thd74.c:916:28: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
         sprintf(cmd, "VD %d", lvl);
                            ^
../../hamlib/kenwood/thd74.c:916:9: note: ‘sprintf’ output between 5 and 11 bytes into a destination of size 10
         sprintf(cmd, "VD %d", lvl);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by denzs** [comment]
Should be good now! :)

**Comment by N0NB** [comment]
Applied and pushed.  Thanks,  Sebastian.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by denzs** [comment]
Thank you for merging! :)

**Comment by denzs** [comment]
How do you think about merging it into 3.x too?

**Comment by N0NB** [comment]
* On 2019 24 Jan 05:10 -0600, Sebastian Denz wrote:
> How do you think about merging it into 3.x too?
> 

Didn't this model require the incompatible 64 bit changes?  Also, I
closed 3.x to new models.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: http://www.n0nb.us  GPG key: D55A8819  GitHub: N0NB

**Comment by denzs** [comment]
Alright! Til now i did not implement the 64 bit change.. i've seen it was discussed, but i didnt notice it was already merged! I'll have a look on that and propably add it too then...

**Pull request merged**
