### PR TITLE
Fixing #48 "Create new rig for Raspberry Pi GPIO pins"

### PR DESCRIPTION
**Pull request by bence98**
Added a new backend for controlling the PTT via a Raspberry Pi pin, using the wiringPi library. If you don't have it (ex. you're building on a PC and not a RPi or compatible), Autoconf should disable it, so this PR shouldn't affect you negatively (yes, I did test it on PC too).

It was tested on a RPi v2 B, revision 1.1 board running Raspbian Jessie (Linux 4.1.7-v7) and wiringPi 2.24, confirmed working with `rigctl`.

You can change the pin numbers in `rpi/rpi.h`, by default it is pin 0 for PTT out and pin 2 for DCD in. (On my board, those are the 6th and 7th pins from the left on the bottom row, if you hold the device so that you can read the "Raspberry Pi 2 Model..." label. For more info, see [wiringPi's website](http://wiringpi.com/pins/).)

73 de [HA5KFU](https://ha5kfu.sch.bme.hu/about/) amateur radio club

### CODE REVIEW

**Comment by N0NB** [comment]
I'm not sure if you saw this message that was posted to the hamlib-developer mailing list:

```
Hi Bence,                                                                                                                           
                                                                                                                                    
are you aware that there is already support for GPIO PTT and DCD. It is not a                                                       
separate backend, just specify the right device path for PTT or DCD to use it                                                       
with any other rig backend being used for CAT. It is not dependent on any                                                           
library as it uses /sys/class/gpio/... to access the GPIO pins and direction                                                        
registers.                                                                                                                          
                                                                                                                                    
73                                                                                                                                  
Bill                                                                                                                                
G4WJS.                                                                                                                              
```

**Comment by bence98** [comment]
No I have not, but thanks! I now subscribed onto the list and will reply to him.

**Comment by mdblack98** [comment]
Bence -- do you want to cancel this pull request?

**Comment by mdblack98** [comment]
Capability already in hamlib -- closing issue

**Comment by bence98** [comment]
Yes, sorry. I tested the built-in GPIO support and it works now.

**Pull request closed without merging**
