### PR TITLE
Add INDI rotator backend

### PR DESCRIPTION
**Pull request by nonoo**
This backend lets Hamlib control an astronomical (telescope) rotator through an
INDI (https://indilib.org/) server.

### CODE REVIEW

**Comment by N0NB** [comment]
This pull breaks `make distcheck` and the MinGW cross-platform builds for Windows.

**Comment by nonoo** [comment]
`make distcheck` works for me under Linux. I have not tested it under Windows, but I'll look at it shortly. Can you please post the errors you see?

**Comment by N0NB** [comment]
After cleaning the repository and running `boostrap` and `configure` and then `make distcheck` with an out of tree build, i.e. in a sibling directory to the `hamlib` directory, the `configure` script fails at:

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating macros/Makefile
config.status: creating include/Makefile
config.status: creating lib/Makefile
config.status: creating src/Makefile
config.status: creating c++/Makefile
config.status: creating bindings/Makefile
config.status: creating doc/Makefile
config.status: creating doc/hamlib.cfg
config.status: creating rotators/amsat/Makefile
config.status: creating rotators/ars/Makefile
config.status: creating rotators/celestron/Makefile
config.status: creating rotators/cnctrk/Makefile
config.status: creating rotators/easycomm/Makefile
config.status: creating rotators/ether6/Makefile
config.status: creating rotators/fodtrack/Makefile
config.status: creating rotators/gs232a/Makefile
config.status: creating rotators/heathkit/Makefile
config.status: creating rotators/ioptron/Makefile
config.status: creating rotators/m2/Makefile
config.status: creating rotators/meade/Makefile
config.status: creating rotators/prosistel/Makefile
config.status: creating rotators/rotorez/Makefile
config.status: creating rotators/sartek/Makefile
config.status: creating rotators/spid/Makefile
config.status: creating rotators/ts7400/Makefile
config.status: error: cannot find input file: `rotators/indi/Makefile.in'
make: *** [Makefile:821: distcheck] Error 1
```

I am testing this on Debian 10 at the moment.

**Comment by nonoo** [comment]
Strange. I've just cloned a clean Hamlib repo and ran `bootstrap` and `configure` and I see no errors. I'm using Ubuntu.

**Comment by mdblack98** [comment]
Try now.

 

    On Wednesday, November 18, 2020, 08:48:08 AM CST, Nate Bargmann <notifications@github.com> wrote:  
 
 


After cleaning the repository and running boostrap and configure and then make distcheck with an out of tree build, i.e. in a sibling directory to the hamlib directory, the configure script fails at:
configure: creating ./config.status
config.status: creating Makefile
config.status: creating macros/Makefile
config.status: creating include/Makefile
config.status: creating lib/Makefile
config.status: creating src/Makefile
config.status: creating c++/Makefile
config.status: creating bindings/Makefile
config.status: creating doc/Makefile
config.status: creating doc/hamlib.cfg
config.status: creating rotators/amsat/Makefile
config.status: creating rotators/ars/Makefile
config.status: creating rotators/celestron/Makefile
config.status: creating rotators/cnctrk/Makefile
config.status: creating rotators/easycomm/Makefile
config.status: creating rotators/ether6/Makefile
config.status: creating rotators/fodtrack/Makefile
config.status: creating rotators/gs232a/Makefile
config.status: creating rotators/heathkit/Makefile
config.status: creating rotators/ioptron/Makefile
config.status: creating rotators/m2/Makefile
config.status: creating rotators/meade/Makefile
config.status: creating rotators/prosistel/Makefile
config.status: creating rotators/rotorez/Makefile
config.status: creating rotators/sartek/Makefile
config.status: creating rotators/spid/Makefile
config.status: creating rotators/ts7400/Makefile
config.status: error: cannot find input file: `rotators/indi/Makefile.in'
make: *** [Makefile:821: distcheck] Error 1

I am testing this on Debian 10 at the moment.

**Comment by nonoo** [comment]
Commit 905cf4e broke configure for me. Seems like you've added rotators/indi to the ROT_BACKEND_LIST variable, but it should only be added if INDI support is available (line 402 adds rotators/indi to the ROT_BACKEND_LIST). Also all line endings has been changed from UNIX to DOS, do you really wanted to do this?

I'll try compiling on Debian and with MinGW on  Windows shortly.

**Comment by nonoo** [comment]
Here's what I've tried in Windows 7 in an MSYS shell using MinGW, and under Debian (Jessie):

git clone https://github.com/Hamlib/Hamlib/
cd Hamlib
git checkout 8ba011e
./bootstrap
./configure

Configure throws no errors, works perfectly both under Win and Debian.

Please re-clone your repo, or run `git clean -dfx` before running bootstrap. Also make sure you try with commit `8ba011e` as the current HEAD breaks configure for me.

**Pull request merged**
