### PR TITLE
Some vfo preparation commits to support Icom SATMODE 

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
Everything looks good so far, Mike.  Let me know when you're done with this set.

**Comment by mdblack98** [comment]
Lots more to come. Fixing tons of debug statements right now and I have an IC9700 coming from Icom (a loaner) to finish the satmode changes. So maybe by Christmas.

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 29, 2019 at 2:35 PM, Nate Bargmann<notifications@github.com> wrote:   
Everything looks good so far, Mike. Let me know when you're done with this set.

**Comment by N0NB** [comment]
On 2019-11-29 20:41, Michael Black wrote:
> Lots more to come. Fixing tons of debug statements right now and I
> have an IC9700 coming from Icom (a loaner) to finish the satmode
> changes. So maybe by Christmas.

so far looks very good Mike! (results are sent private)

R.

**Comment by N0NB** [comment]
Everything is applied and pushed.  Thanks Mike, that was quite a
contribution!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Pull request merged**
