### PR TITLE
ic746.c: fix ic746pro_get_channel() and implement ic746pro_set_channel()

### PR DESCRIPTION
**Pull request by ra1nb0w**
for ic746pro_get_channel()
- pb variable is signed
- fix struct length enabling dcs.pol (fix description)
- add split correct configuration
- remove duplicated name description on csv

for ic746pro_set_channel()
- implement the function to re-write the saved csv
- tested with IC-7400 (aka IC-746Pro)
- if in the line the frequency or mode is empty or 0 the memory will be cleared

Closes: https://github.com/Hamlib/Hamlib/issues/125

### CODE REVIEW

**Comment by ra1nb0w** [comment]
was accidentally introduced with https://github.com/Hamlib/Hamlib/commit/4072f9f4a57c4b049a2715f6f2ce315e3f2af4db
With that change the csv has two `channel_desc` and the second it is useless.
I discussed privatelly with @mdblack98 about that patch and I removed those part but unfortunately it reached upstream.
if you like, I can rebase this PR and create a single commit for that change.

**Comment by N0NB** [comment]
* On 2020 21 Jan 01:02 -0600, rainbow wrote:
> was accidentally introduced with https://github.com/Hamlib/Hamlib/commit/4072f9f4a57c4b049a2715f6f2ce315e3f2af4db
> With that change the csv has two `channel_desc` and the second it is useless.
> I discussed privatelly with @mdblack98 about that patch and I removed those part but unfortunately it reached upstream.
> if you like, I can rebase this PR and create a single commit for that change.

Yes, please rebase this so it is more clear.

Thanks!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by ra1nb0w** [comment]
done

**Comment by N0NB** [comment]
I think you'll need to close this request and open a new one with just the latest commit of 9dba7cf as my fresh pull still includes the changes to `tests/memcsv.c` and `tests/memsave.c`, i.e., commit 38d76f3, which i don't want to apply.

**Comment by ra1nb0w** [comment]
the change to `tests/memcsv.c` and `tests/memsave.c` must be merged; in essence the csv produced by master is broken (out of spec). Why you don't want to apply? I explained https://github.com/Hamlib/Hamlib/pull/182#issuecomment-576545639 why this is wrong and that code arised from a private discussion with @mdblack98 about the fact that the `save` command of rigmem didn't store `channel_desc` field. This problem was because the struct `channel_str_t` was too shoort when `membuf` is casted and parsed. Moreover, you can easily see the timing of these facts and the code speak alone about the duplication (use `git blame`). As you requested, I divided the commit to clarify the fix.

The `ic746pro_set_channel()` commit doesn't work without the other two.

**Comment by ra1nb0w** [comment]
if you don't see the free commits; force the pull.

**Comment by mdblack98** [comment]
He's right Nate...go ahead and merge....he's just removing the accidental duplicate I put in.
Mike 

    On Tuesday, January 21, 2020, 08:43:59 AM CST, rainbow <notifications@github.com> wrote:  
 
 
the change to tests/memcsv.c and tests/memsave.c must be merged; in essence the csv produced by master is broken (out of spec). Why you don't want to apply? I explained #182 (comment) why this is wrong and that code arised from a private discussion with @mdblack98 about the fact that the save command of rigmem didn't store channel_desc field. This problem was because the struct channel_str_t was too shoort when membuf is casted and parsed. Moreover, you can easily see the timing of these facts and the code speak alone about the duplication (use git blame). As you requested, I divided the commit to clarify the fix.

The ic746pro_set_channel() commit doesn't work without the other two.

**Comment by N0NB** [comment]
* On 2020 21 Jan 08:55 -0600, Michael Black wrote:
> He's right Nate...go ahead and merge....he's just removing the accidental duplicate I put in.

Okay.

I am dividing my time between this and the other things in life so I'm
not paying all that close of attention to these long threads.  When I
get some time I start looking things over and then questions arise.

Thanks for the info, both of you.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by N0NB** [comment]
I am seeing the following warning from GCC:

```
  CC       ic746.lo
../../../hamlib/rigs/icom/ic746.c: In function ‘ic746pro_set_channel’:
../../../hamlib/rigs/icom/ic746.c:1140:7: warning: ‘stpncpy’ output may be truncated copying 9 bytes from a string of length 29 [-Wstringop-truncation]
       stpncpy(membuf.name, chan->channel_desc, sizeof(membuf.name));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and clang gives this warning output:

```
  CC       ic746.lo
../../../hamlib/rigs/icom/ic746.c:987:41: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
        chan->split = membuf->chan_flag && 0x10 ? RIG_SPLIT_ON : RIG_SPLIT_OFF;
                                        ^  ~~~~
../../../hamlib/rigs/icom/ic746.c:987:41: note: use '&' for a bitwise operation
        chan->split = membuf->chan_flag && 0x10 ? RIG_SPLIT_ON : RIG_SPLIT_OFF;
                                        ^~
                                        &
../../../hamlib/rigs/icom/ic746.c:987:41: note: remove constant to silence this warning
        chan->split = membuf->chan_flag && 0x10 ? RIG_SPLIT_ON : RIG_SPLIT_OFF;
                                       ~^~~~~~~
1 warning generated.
```

**Comment by ra1nb0w** [comment]
My clang was silent.
- fixed `&&` also in another line.
- `stpncpy` is correct and the intended behaviour but gcc has decided to issue a warning  (see https://bugzilla.redhat.com/show_bug.cgi?id=1431678#c5 and https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html); changed with `memcpy` that should avoid the warning.

**Pull request merged**
